#!/usr/bin/env bash

all_ipfs_cluster_git=git://github.com/ipfs/ipfs-cluster
all_ipfs_cluster_ref="11a8926236afe119ab78bc583cd8b272e762d86e"

# Identities of the nodes. The private keys are hidden away in the secrets unit.
pluto_ipfs_cluster_peerid="QmSiW1LpXRzbkuhjSABTJBJd9zb5vckVofbTFLjH5fmrM5"
neptune_ipfs_cluster_peerid="QmQBriDc5ZNAHdYzC9gAZ17s1eJvenp5SUzHnZMv65pnJH"
uranus_ipfs_cluster_peerid="QmQEn69dRXLENMaV33f2MRAqNg4u1GwzjisWr4ewQ4B974"
saturn_ipfs_cluster_peerid="QmNWGCZe8StGiJ6G4HKqmB3YkMVPoQvbPqE6yo8paQddVP"
jupiter_ipfs_cluster_peerid="QmTVCTKnCueMz95ifXC81jQZyX9e43cDT9AXnGcjd71XoU"
venus_ipfs_cluster_peerid="QmQfpaSGNkXtMHD3UyLUUWcaKquT4hA1h42wcPxZXtXdeT"
earth_ipfs_cluster_peerid="QmWZEJm76A7v8qBXKQcFKcGFA982Qwhzz6zZMakRMoVWZo"
mercury_ipfs_cluster_peerid="QmUpZtr7MhrkZCZRPjG3xoL4ocpy1v1JNuvnhnfv5mGhYs"
scrappy_ipfs_cluster_peerid="QmRjdKMdQbvhjiXVncoC9pdouFoJcxRxXy78Ucd2XdnoSS"
chappy_ipfs_cluster_peerid="QmXYzjACnh4yZPYcm93TJLcFLh4MdBJCN3tK7uVMnLCmPQ"


# Historical location, TODO: move to /mnt/data/ipfs
all_ipfs_cluster_data=/ipfs/ipfs-cluster
